database:
  mongo:
    information: "mongodb://localhost:27017/"
    database: "arvan_db"
logging:
    file_name: "log_information.log"
    mode: "a"
    format: '%(name)s - %(process)d - %(pathname)s - %(lineno)d - %(levelname)s - %(message)s - %(asctime)s'
    date_format: "%d-%b-%y %H:%M:%S"
bucket:
  access_key: "*****"
  secret_key: "*****"
  endpoint: "*****"
  service_name: "***"

